- hosts: nodes
  user: root
  vars:
    MasterConfigFile: /etc/origin/master/master-config.yaml
  tasks:
   - name: Check existence of master config file {{ MasterConfigFile }}
     stat:
       path: '{{ MasterConfigFile }}'
     register: masterconfig_file

   - name: Configure Image Provenance Plugin in {{ MasterConfigFile }} for TSS 9.7
     lineinfile:
       path: '{{ MasterConfigFile }}'
       insertafter: "pluginConfig:"
       line: '    openshift.io/ImagePolicy:'
     when: masterconfig_file.stat.exists     

