- hosts: nodes
  user: root
  vars:
    MasterConfigFile: /etc/origin/master/master-config.yaml
    imageProvenancePluginFile: image-Provenance-plugin.template
  tasks:
   - name: Check existence of master config file {{ MasterConfigFile }}
     stat:
       path: '{{ MasterConfigFile }}'
     register: masterconfig_file

   - name: remove the existing ImagePolicy section
     replace:
       path: '{{ MasterConfigFile }}'
       regexp: '^(\s+).openshift.io/ImagePolicy:(.*\n)*(\s+).kind: ImagePolicyConfig$(.*\n)'
       backup: true
     when: masterconfig_file.stat.exists

   - name: Configure Image Provenance Plugin in {{ MasterConfigFile }} for TSS 9.7
     blockinfile:
       path: '{{ MasterConfigFile }}'
       insertafter: "pluginConfig:"
       block: "{{ lookup('template', '{{ imageProvenancePluginFile }}') }}"
       marker: "# {mark} ANSIBLE MANAGED BLOCK - Image-Provenance-plugin section"
       state: present
     when: masterconfig_file.stat.exists

   - name: Restart Openshift master service
     shell: >
       master-restart api
     when: masterconfig_file.stat.exists

# Note: About the port number ;-)
#       Use this command (or one similar) to get the actual PORT number.
#         >>>>  oc whoami --show-server|sed 's/.*://'
#       rather than hard-coding it in the "url:"
   - name: master-api healthcheck
     uri:
#       url: https://127.0.0.1/healthz
       url: https://127.0.0.1:8443/healthz
       method: GET
       validate_certs: no
       follow_redirects: yes
       return_content: yes
     register: _response
     until: _response.status == 200
     retries: 300
     delay: 2
     when: masterconfig_file.stat.exists
     
