- hosts: nodes
  user: root
  vars:
    MasterConfigFile: /etc/origin/master/master-config.yaml
  tasks:
   - name: Check existence of master config file {{ MasterConfigFile }}
     stat:
       path: '{{ MasterConfigFile }}'
     register: masterconfig_file

   - name: Configure apiServerArgument section in {{ MasterConfigFile }} for TSS 4.35 and TSS 6.6
     blockinfile:
       path: '{{ MasterConfigFile }}'
       insertafter: "apiServerArguments:"
       block: |2
             feature-gates:
               - AdvancedAuditing=true
               - RotateKubletServerCertificate=true
       state: present
       marker: "# {mark} ANSIBLE MANAGED BLOCK - apiServerArgument section"
     when: masterconfig_file.stat.exists
