- hosts: nodes
  user: root
  vars:
    NodeConfigFile: /etc/origin/node/node-config.yaml
  tasks:
   - name: Check existence of node config {{ NodeConfigFile }}
     stat:
       path: '{{ NodeConfigFile }}'
     register: nodeconfig_file

   - name: Configure event-qps section in {{ NodeConfigFile }} for TSS 10.11
     blockinfile:
       path: '{{ NodeConfigFile }}'
       insertafter: "kubeletArguments:"
       block: |2
           event-qps:
           - '0'
       state: present
       marker: "# {mark} ANSIBLE MANAGED BLOCK - event-qps section"
       backup: true
     when: nodeconfig_file.stat.exists

   - name: Restart kubelet service
     shell: >
       systemctl restart atomic-openshift-node
     when: nodeconfig_file.stat.exists
